
server:
  port: 5001

spring:
  application:
    name: user-service
  # Data source and connection properties
  datasource:
    url: jdbc:mysql://localhost:3308/lms-user-service-db
    username: user
    password: pwd
    hikari.initializationFailTimeout: 60000
    initialization-mode: always
    maximum-pool-size: 10
    continue-on-error: true
  # Strongly recommend to set this property to "none" in a production environment!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC


logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-user-service/lms-user-service-db

server:
  port: 8080
